import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Learning Next js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body>
        
        {children}
       
      </body>  
      
    </html>
  );
}
